### PR TITLE
updating tutorial throughout

### PR DESCRIPTION
**Pull request by stefaniebutland**
updating images, fixing open issues reported by users

### CODE REVIEW

**Comment by stefaniebutland** [comment]
UPDATE: yes, I need to submit PR to update Faylab instructions

as noted in Faylab manual forking instructions lead to forking main branch only (screenshot). Does this reproduce [this problem](https://github.com/Openscapes/quarto-website-tutorial/issues/25#issuecomment-1779812058)? If so, submit PR to faylab manual repo to update

Screenshot 2023-12-18 at 11 43 54 AM

**Comment by stefaniebutland** [comment]
Updated Faylab lab manual wiki - [Quick steps to making a copy of the lab manual & publishing it](https://github.com/thefaylab/lab-manual/wiki/Quick-steps-to-making-a-copy-of-the-lab-manual-&-publishing-it)- indicating to uncheck `cp main branch only`.  (took a while, I forked the whole manual, made PR to wiki and couldn't find it. Finally edited the wiki page directly )

**Comment by stefaniebutland** [comment]
🤔 

Screenshot 2023-12-18 at 1 32 50 PM

**Comment by jules32** [comment]
@stefaniebutland that checkbox "use your github pages website" is asking whether you'd like it to auto-fill the url in the "Website" field just above (it used to make you type it all out). So now you have the option to essentially auto-fill with the github.io url for the repository; I don't think this is related to github actions.

**Pull request merged**
